apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      kind: Backup
      name: nextcloud-backup
    patch: |-
      - op: replace
        path: /spec/schedule/suspend
        value: true