apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-owner
type: Opaque
stringData:
  username: <path:k8s-secrets/data/nextcloud#cnpg-owner-username>
  password: <path:k8s-secrets/data/nextcloud#cnpg-owner-password>
