apiVersion: apps/v1
kind: Deployment
metadata:
  name: urbackup-client
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: urbackup-client
  template:
    metadata:
      labels:
        app: urbackup-client
    spec:
      containers:
      - env:
        - name: URBACKUP_SERVER_NAME
          value: <path:k8s-secrets/data/common#urbackup-dsn>
        - name: URBACKUP_CLIENT_NAME
          value: nextcloud
        - name: URBACKUP_CLIENT_AUTHKEY
          value: <path:k8s-secrets/data/nextcloud#urbackup_client_authkey>
        image: uroni/urbackup-client:latest
        name: urbackup-client
        volumeMounts:
        - mountPath: /usr/local/var/urbackup
          name: urbackup           
        - mountPath: /backup
          name: nextcloud-data
        - mountPath: /backup/nextcloud
          name: nextcloud
        - mountPath: /backup/mariadb
          name: mariabackup
      volumes:
      - name: urbackup
        persistentVolumeClaim:
          claimName: urbackup          
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data-squid
      - name: nextcloud
        persistentVolumeClaim:
          claimName: nextcloud-squid
      - name: mariabackup
        persistentVolumeClaim:
          claimName: mariabackup-squid
