apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mariabackup-squid-pvc.yaml
- mariadb-secret.yaml
- nextcloud-secret.yaml
- nextcloud-data-squid-pvc.yaml
- nextcloud-squid-pvc.yaml
- redis.yaml
- nextcloud-mariadb.yaml
- nextcloud-ir.yaml
- nextcloud-backup.yaml
#
- nextcloud-cnpg-owner-secret.yaml
- nextcloud-cnpg-superuser-secret.yaml
- rgw-credentials-secret.yaml
- nextcloud-pg-cluster.yaml
