apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariabackup
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: cephfs-hdd-r2-noexport
  volumeMode: Filesystem

