apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  annotations:
    avp.kubernetes.io/path: "k8s-secrets/data/nextcloud"    
stringData:
  password: <password>
  root-password: <root-password>
  db-username: <db-username>
  db-password: <db-password>
