apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  # annotations:
    # avp.kubernetes.io/path: "k8s-secrets/data/nextcloud"    
stringData:
  password: <v1/k8s-secrets/data/nextcloud#password>
  root-password: <v1/k8s-secrets/data/nextcloud#root-password>
  db-username: <k8s-secrets/data/nextcloud#db-username>
  db-password: <k8s-secrets/data/nextcloud#db-password>
