apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/nextcloud"    
stringData:
  password: <mariadb-password>
  root-password: <mariadb-root-password>
  db-username: <db-username>
  db-password: <db-password>
