apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-squid
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: cephfs-hdd-r2-noexport-squid
  volumeMode: Filesystem

