apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-pgsql-secret
  annotations:
    avp.kubernetes.io/path: "k8s-secrets/data/nextcloud"    
stringData:
  db-username: <cnpg-owner-username>
  db-password: <cnpg-owner-password>
