apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/nextcloud"     
stringData:
  nextcloud-password: <nextcloud-password>
  nextcloud-username: <nextcloud-username>
  smtp-host: <smtp-host>
  smtp-password: <smtp-password>
  smtp-username: <smtp-username>
  
