apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: nextcloud-backup
spec:
  mariaDbRef:
    name: nextcloud-mariadb
  schedule:
    cron: "15 00 * * *"
    suspend: false
  maxRetention: 720h # 30 days
  storage:
    volume:
      persistentVolumeClaim:
        claimName: mariabackup
  args:
  - --single-transaction
    # - --databases nextcloud    
  - --all-databases
  logLevel: info
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi