apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-cnpg-superuser
type: Opaque
stringData:
  username: <path:k8s-secrets/data/common#cnpg-superuser-username>
  password: <path:k8s-secrets/data/common#cnpg-superuser-password>
