apiVersion: v1
kind: Secret
metadata:
  name: rgw-credentials
type: Opaque
stringData:
  ACCESS_KEY_ID: <path:k8s-secrets/data/common#rgw-access-key-id>
  SECRET_ACCESS_KEY: <path:k8s-secrets/data/common#rgw-secret-access-key>